### ISSUE TITLE
bson.decode_all() not working anymore

### ISSUE THREAD

**Issue by lorenzznerol** [py-bson/bson#102]
import bson
with open('xyz.bson','rb') as f:
    data = bson.decode_all(f.read())

This worked just a week ago with another bson version probably, now after re-installing Python and IDE, I get 

> AttributeError: module 'bson' has no attribute 'decode_all'

 using bson 0.5.10

I also refer to https://stackoverflow.com/questions/27527982/read-bson-file-in-python which mentions this approach. If the decode_all is not available anymore, please inform.

**Comment by Parkayun** [comment]
pybson doesn't have `decode_all` method.

**Comment by PrimozGodec** [comment]
@lorenzznerol, you probably used bson module from `pymongo` package. It has same import but a different API. 

To use `decode_all` install `pymongo` with:

```
pip install pymongo
````
