### ISSUE TITLE
bson is slow

### ISSUE THREAD

**Issue by williame** [py-bson/bson#12]
from: http://stackoverflow.com/questions/9884080/fastest-packing-of-data-in-python-and-java

test_struct encoding took 0.6742, decoding 0.5187
test_json_1 encoding took 0.6256, decoding 0.9847
test_bson encoding took 56.1082, decoding 30.1189
test_json_2 encoding took 0.7145, decoding 0.8737
test_pickle encoding took 8.8269, decoding 9.9774
test_cPickle encoding took 1.1699, decoding 1.4753
test_marshal encoding took 0.1216, decoding 0.5035

**Comment by Parkayun** [comment]
It closed via #44
