### ISSUE TITLE
Still being maintained???

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [py-bson/bson#127]
It looks like there hasn't been any activity in here for a good while.

As far as I know, it's still working with modern Python, but there are some issues with build system and all that (see #125, for example).

If you want to maintain it, I (and probably others) can help with PRs, etc, but I'm not going to workon that unless someone says they's review and merge.

What shoudl be done (incomplete list):
- update build to pyproject.toml
- probably remove six and Py2 support
- test with python 3.9 -- 3.12 (3.13?)
- Add CI support -- a simple gitHub actions for the tests should ber pretty easy to set up.

Move to 1.0?

**Comment by Kludex** [comment]
I'm happy to review PRs... Please small ones so we can iterate faster.

**Comment by stankudrow** [comment]
> I'm happy to review PRs... Please small ones so we can iterate faster.

Hello, let's review this PR (#126 ), shall we?

**Comment by Kludex** [comment]
What's this "shall we" about? 🤔

Smaller PRs will speed up reviews, and I can make more meaningful review as well.

**Comment by Kludex** [comment]
You seem to talk as if I have an obligation here.

Please break the PRs. It's more about the logical separation rather than the size. There's a change in how to build, the formatter, the CI...

On the package manager, I'd prefer to move to uv + hatchling as most of the ecosystem.

**Comment by stankudrow** [comment]
> You seem to talk as if I have an obligation here.
> 
> Please break the PRs. It's more about the logical separation rather than the size. There's a change in how to build, the formatter, the CI...
> 
> On the package manager, I'd prefer to move to uv + hatchling as most of the ecosystem.

No problem + learn about 'uv' (will be the first attempt).

**Comment by Kludex** [comment]
Thanks. 🙏 

You can get inspiration from https://github.com/Kludex/python-multipart/blob/master/pyproject.toml, if it helps.

**Comment by PythonCHB** [comment]
Note:

Formatting changes can make a mess of the history, so I’d suggest either:

1) don’t do it unless that section of the code ids being touched for another reason.

or

2) put all the formatting updates in a single commit, with no other changes.

In either case, @Kludex can tell us what format style to prefer: black? Ruff? Just PEP 8, etc. 

Also, could folks out here (or a new issue) what updates they are working on, so we don’t duplicate effort?

**Comment by stankudrow** [comment]
> Note:
> 
> Formatting changes can make a mess of the history, so I’d suggest either:
> 
>     1. don’t do it unless that section of the code is being touched for another reason.
> 
> 
> or
> 
>     2. put all the formatting updates in a single commit, with no other changes.
> 
> 
> In either case, @Kludex can tell us what format style to prefer: black? Ruff? Just PEP 8, etc.
> 
> Also, could folks put here (or a new issue) what updates they are working on, so we don’t duplicate effort?

I can only guess, but it is probable to be ruff, which is not only a linter (replacing many of them), but also a formatter (and this can make black obsolete) + the wish for the uv as a project manager.

**Comment by ChrisBarker-NOAA** [comment]
> you think it would be a bad step to present a PR with only linted code?

Sorry for the confusion -- no, that would be a good idea -- do all the re-formatting at once, commit that, and then do a PR of that, and only that. no other changes in that PR.

**Comment by Kludex** [comment]
> Formatting changes can make a mess of the history, so I’d suggest either:
> 
> 1. don’t do it unless that section of the code is being touched for another reason.

We can use the `.git-blame-ignore-revs` - I'm okay with it.

 > In either case, @Kludex can tell us what format style to prefer: black? Ruff? Just PEP 8, etc.
 
 Following the [python-multipart](https://github.com/Kludex/python-multipart/blob/master/pyproject.toml) practices would be great.

**Comment by Kludex** [comment]
If possible, I'd like to start with having a pipeline, so we can speed up those changes as per https://github.com/py-bson/bson/pull/129#issuecomment-2550899196.

**Comment by Kludex** [comment]
To answer the title: I'm here.
