### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by amm042** [py-bson/bson#26]
when doing basic install on python3, it succeeds with errors:

  $ sudo easy_install3 bson 
  Searching for bson
  Reading https://pypi.python.org/simple/bson/
  Best match: bson 0.3.3
  Downloading https://pypi.python.org/packages/source/b/bson/bson-0.3.3.tar.gz#md5=46bce086741b651afaba0ea118fc5f8d
  Processing bson-0.3.3.tar.gz
  Writing /tmp/easy_install-76jcw__x/bson-0.3.3/setup.cfg
  Running bson-0.3.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-76jcw__x/bson-0.3.3/egg-dist-tmp-bjatn5jv
    File "build/bdist.linux-x86_64/egg/bson/network.py", line 6
    except ImportError, e:
                      ^
  SyntaxError: invalid syntax

    File "build/bdist.linux-x86_64/egg/bson/codec.py", line 87
      except KeyError, e:
                     ^
  SyntaxError: invalid syntax

  zip_safe flag not set; analyzing archive contents... 
  Adding bson 0.3.3 to easy-install.pth file

  Installed /usr/local/lib/python3.4/dist-packages/bson-0.3.3-py3.4.egg
  Processing dependencies for bson
  Finished processing dependencies for bson

However, when you import bson it fails:
$ ipython3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import bson
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-06b0a290ed7c> in <module>()
----> 1 import bson

/usr/local/lib/python3.4/dist-packages/bson-0.3.3-py3.4.egg/bson/__init__.py in <module>()
     52 """
     53 
---> 54 from codec import *
     55 import network
     56 __all__ = ["loads", "dumps"]

ImportError: No module named 'codec'

**Comment by stevei101** [comment]
I submitted a pull request to fix this https://github.com/martinkou/bson/pull/28

**Comment by Parkayun** [comment]
I added code(4650b6b878d8e1dc3b0fd605ae84daac29f042df).
In version 0.4, It will work fine in Python3.

**Comment by Parkayun** [comment]
Now, bson support Python3!
