### ISSUE TITLE
Installing the package messes up pymongo

### ISSUE THREAD

**Issue by eli-b** [py-bson/bson#29]
Pymongo installs its own bson package directly to site-packages (not into pymongo/bson for some reason). Accidentally installing this package causes pymongo imports like this to fail:
`from bson.errors import *`

**Comment by nicklasb** [comment]
Yes, there seem to have a serious conflict here. 

Even though this might be a strange choice by MongoDB and not the fault of this library, there are a huge number of people using the mongodb python driver, and changing *that* may cause serious problems. Yes, changing this might too, but less, and the common good must be considered IMO. 

There must be some way these two projects can coexist, perhaps they can block each others installations? Please communicate with MongoDB and try to find some solution.

**Comment by eli-b** [comment]
So you'd be willing to check if Pymongo is installed during the setup of pybson and fail if it is?
If so, I could ask the Pymongo devs to do the same thing.

**Comment by nicklasb** [comment]
@eli-b Me?

**Comment by eli-b** [comment]
Whoever's most responsive to tickets :P

**Comment by nicklasb** [comment]
Too bad it was me then, as I'm not involved in either project. :-)

**Comment by Parkayun** [comment]
Umm... I don't have nice idea for this issue until now.

**Comment by eli-b** [comment]
Now that @nicklasb has come up with the idea of just making sure neither package steps on the toes of the other, would you agree to it? I think it means refusing to install the package if Pymongo is already installed.

**Comment by Parkayun** [comment]
Yep, I will add something like refusing feature or caution statements when install this package.
Thanks, both of you.

**Comment by nicklasb** [comment]
Yeah, and a really explanatory error message in addition to the failure
would be icing on the cake.

Glad to help!

**Comment by PhanindraPanthagani** [comment]
@Parkayun  can you please tell whats the final fix ? I am still getting the error : 
AttributeError: module 'bson' has no attribute 'BSON'

**Comment by Parkayun** [comment]
This project has been for use bson module without mongodb driver.
And this package's description and purpose is `Independent BSON codec for Python that doesn't depend on MongoDB.`.
So, I strongly suggest to don't use this package with `pymongo`.
