### ISSUE TITLE
python 3.4.3 dumps fails to serialize binary data

### ISSUE THREAD

**Issue by positivcheg94** [py-bson/bson#32]
python 2.7.10 - dumps and loads are OK
python 3.4.3 - loads OK, dumps fails to serialize binary data
>>> import bson
>>> message = b'qwerty'
>>> dumped = bson.dumps({'d':message})
>>> des_message = bson.loads(dumped)
>>> des_message
{}
>>>

**Comment by Parkayun** [comment]
I fixed this bug and uploaded 0.4.1 to PyPI.

Thanks.
