### ISSUE TITLE
Exception: 'KeyError: 7'

### ISSUE THREAD

**Issue by pbassut** [py-bson/bson#38]
```bash
>>> import bson
>>> bson.loads(open('/Users/patrickbassut/Documents/dump/myfc_id/account.bson', 'r').read())
  File "<stdin>", line 1, in <module>
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/bson/__init__.py", line 45, in loads
    return decode_document(data, 0)[1]
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/bson/codec.py", line 279, in decode_document
    base, name, value = decode_element(data, base)
  File "/Users/patrickbassut/Programming/paymant/lib/python2.7/site-packages/bson/codec.py", line 265, in decode_element
    element_description = ELEMENT_TYPES[element_type]
KeyError: 7
```

This might be very specific to what I'm trying to read. But unfortunately is very sensitive information so I can't provide it.

**Comment by Parkayun** [comment]
@pbassut Could you show me sample of your bson file what raise exception?

**Comment by veich** [comment]
@pbassut same here... did you find out what was the problem?

**Comment by oliverbienert** [comment]
I have the same problem:
```
with open("person.bson", "rb") as infile:
    bson = bson.loads(infile.read())
```
Attached the file in question.
[person.bson.zip](https://github.com/py-bson/bson/files/206111/person.bson.zip)

Oliver

**Comment by Parkayun** [comment]
@oliverbienert Thanks :+1:

**Comment by Parkayun** [comment]
@oliverbienert It seems wrong bson type. How can do you encode that data set?

**Comment by Parkayun** [comment]
I opened issue #39 .

**Comment by Parkayun** [comment]
I did upload 0.4.4 to PyPI for this issue.
It supports ObjectID. But, not fully support (will be done on 0.5).
