### ISSUE TITLE
Support ObjectId element type

### ISSUE THREAD

**Issue by Parkayun** [py-bson/bson#39]
refer with #38

**Comment by oliverbienert** [comment]
The file I posted with https://github.com/py-bson/bson/issues/38 is a mongodb dump, as far as I know. You can download more of those files at https://politik-bei-uns.de/daten. Unfortunately, it is german only, but you'll see the download links at once.

**Comment by Parkayun** [comment]
@oliverbienert Thanks :)

**Comment by petri** [comment]
How about pillaging the ObjectId implementation from pymongo? It's easy, everything mostly in one Python module :)

**Comment by petri** [comment]
Please see the PR.

**Comment by Parkayun** [comment]
@petri Thanks. I will look for it.

**Comment by Parkayun** [comment]
Closed with #66
