### ISSUE TITLE
pip install bson failing 

### ISSUE THREAD

**Issue by kokhandiar** [py-bson/bson#40]
import bson

  File "bson/__init__.py", line 66, in <module>

    from . import codec

  File "bson/codec.py", line 28, in <module>

    from .objects import *

  File "bson/objects.py", line 36

    class BSONObject(object, metaclass=ABCMeta):

SyntaxError: invalid syntax

**Comment by Parkayun** [comment]
It seems refer with #29 .

**Comment by Jwely** [comment]
I am also experiencing this error.

**Comment by mmarzec** [comment]
me too

**Comment by jeanschmidt** [comment]
24 days, is there any hope for us that this issue will be fixed on current version of pip?

**Comment by Parkayun** [comment]
Have try
`pip install -U bson`
If you have pymongo, then should choice to use(install) between pymongo's and this bson. (cuz, package name is same so it will raise import error.)

**Comment by BeginMan** [comment]
Switch to Python 3.x then you can install it.

```
pyenv local 3.4.3
pip install -U bson
```

Successfully installed bson-1.1.0

**Comment by BeginMan** [comment]
Trying to install pymongo 2.8 to solve this problem.
```
pip install pymongo==2.8
```
Successfully installed pymongo-2.8

```
>>>import bson
```

**Comment by ygbourhis** [comment]
"pip install bson" still tries to pull version 1.1.0
It's the way 1.1.0 was uploaded to pypi which causes this issue, because "pip install bson" should automatically pull 0.4.3 with py2k and 1.1.0 with py3k

**Comment by DaphneHB** [comment]
You have a pretty simple solution there: 
http://stackoverflow.com/questions/35254975/import-error-no-module-named-bson :
$ sudo apt-get purge python-pymongo 
then 
$ sudo apt-get install python-pymongo

Works fine for me! Don't bother for the autoremove asked after the purge command.
