### ISSUE TITLE
Downgrade from 1.1.0 to 0.4.3?

### ISSUE THREAD

**Issue by Perados** [py-bson/bson#48]
Something weird happened to me. I don't know if it is related to bson or to PyPI. I had bson 1.1.0 installed, and I am not dreaming, my requirements.txt shows `bson==1.1.0` and I even checked with my colleague who did not upgraded and he has `bson==1.1.0` when doing `pip freeze | grep bson`.
When I did `pip install --upgrade bson` because `pip install -r requirements.txt` was failing, it installed bson 0.4.3, which is the "current" version.
So, what happened? Is this "downgrade" gonna break many things in my code? Is it just a renaming? Is it related to you or to PyPI? What should I do?

Thank you in advance!

PS: Again, I am not dreaming: https://libraries.io/pypi/bson/1.1.0

**Comment by Parkayun** [comment]
0.4.3 is current version. And 1.1.0 is old version from legacy. so, I deleted it in pypi recently.
Thanks 😄
