### ISSUE TITLE
tag and release 0.4.3 on github 

### ISSUE THREAD

**Issue by bulwahn** [py-bson/bson#49]
Dear Ayun Park,

I maintain a bitbake recipe of your python package at:

https://github.com/bmwcarit/meta-ros/blob/master/recipes-devtools/python/python-bson_0.4.1.bb

This file contains some meta data that allows a cross-compile tool chain to compile and package your python package.

Now, I wanted to update to the most recent version 0.4.3 and noticed that the repository has not been tagged and hence github does not provide an archive of version 0.4.3 for downloading, which my recipe relies on.

Could you please tag the version 0.4.3 in the github repository? Thanks for your work and your effort.

Best regards,

Lukas Bulwahn

**Comment by Parkayun** [comment]
Done :smile:
