### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by fedotoff** [py-bson/bson#60]
Why do you use "unicode" built-in function to decode utf-8 string for Python2.x? Why don't you use method decode with 'utf-8' as argument.
I've got  one case:

```
import bson
doc = {u'саша': u'маша'}
bson.loads(bson.dumps(doc))
```

As I know from http://bsonspec.org/spec.html "string" ('\x02' UTF-8 encoded characters) and cstring not fully but UTF-8 encoded characters (except '\x00')

Can you explain me this case? Maybe I'm wrong.

**Comment by Parkayun** [comment]
It's just legacy codes. I think about to refactor whole code base.
