### ISSUE TITLE
Boolean not decoded anymore since 0.4.4

### ISSUE THREAD

**Issue by pvanderlinden** [py-bson/bson#62]
I expected `bson.loads(bson.dumps({"test": False}))` to result in `{"test": False}`, but since 0.4.4 it results in `{"test": 0}`

**Comment by Parkayun** [comment]
Thanks for your report

**Comment by marfx000** [comment]
Hi, i've fixed this bug and send pull request https://github.com/py-bson/bson/pull/63. Please, take a look on it.

**Comment by pvanderlinden** [comment]
nice, hopefully someone will merge & release it soon

**Comment by Parkayun** [comment]
@pvanderlinden @marfx000 I released 0.4.8 for this issue.
