### ISSUE TITLE
 module 'bson' has no attribute 'BSON'

### ISSUE THREAD

**Issue by othersideoflearning** [py-bson/bson#70]
41             # Grab the image from the product.
---> 42             item = bson.BSON(item_data).decode()
     43             img_idx = image_row["img_idx"]
     44             bson_img = item["imgs"][img_idx]["picture"]

AttributeError: module 'bson' has no attribute 'BSON'

**Comment by lorenzznerol** [comment]
This is perhaps not yet solved?
`bson.BSON(item_data).decode() `
gives me 
`AttributeError: module 'bson' has no attribute 'BSON'`

**Comment by Parkayun** [comment]
see mongodb's bson module

**Comment by lorenzznerol** [comment]
Thank you, it might have been a stupid question. It was and is confusing that both **pymongo** and **bson** packages need the same `import bson` statement when you want to read bson. If you have both bson and pymongo installed, `import bson` will only import the pymongo version (e.g. bson.loads() is not accessible, thus the bson packages are not merged together). You would need to uninstall pymongo just to get the `import bson` from here again and not the pymongo `import bson` package.

**Comment by Parkayun** [comment]
I'm testing another name `pybson`. you can install and use that name.

**Comment by lorenzznerol** [comment]
I have used `pip uninstall bson` and `pip install pybson` now so that I can use `from pybson import bson as ...` if I accidentally need both pymongo's and pybson's `import bson`. I can also use `from pybson import bson` to have the old name back. Thanks.

**Comment by lorenzznerol** [comment]
Now it throws an error: `ModuleNotFoundError: No module named 'bson'` when using `import pybson`

**Comment by lorenzznerol** [comment]
I have installed a new system, using anaconda as the base. In Spyder, even though I had installed bson using "pip install pybson", it said:

> Traceback (most recent call last):
> 
>   File "<ipython-input-1-c4f1361cfac2>", line 1, in <module>
>     import pybson # same as bson
> 
>   File "C:\Users\Admin\anaconda3\lib\site-packages\pybson\__init__.py", line 23, in <module>
>     from .objectid import ObjectId
> 
>   File "C:\Users\Admin\anaconda3\lib\site-packages\pybson\objectid.py", line 30, in <module>
>     from bson.py3compat import PY3, bytes_from_hex, string_type, text_type
> 
> ModuleNotFoundError: No module named 'bson'

After installing pymongo in addition to pybson, using `conda install pymongo`, the `import pybson` statement worked. Why?
