### ISSUE TITLE
int with value > 7FFFFFFFFFFFFFFF not supported

### ISSUE THREAD

**Issue by Bezbran** [py-bson/bson#71]
The bug is in codec.py file:
`            if value < -0x80000000 or value > 0x7fffffff:
                buf.write(encode_int64_element(name, value))`

`def encode_int64_element(name, value):
    return b"\x12" + encode_cstring(name) + struct.pack("<q", value)`

**struct.pack("<q", 0x8fffffff)** raises "{error}required argument is not an integer"

In [(BSON specs)](http://bsonspec.org/spec.html) Uint64 is indeed supported:

"\x11" e_name uint64

**Comment by Parkayun** [comment]
Released on 0.5.1
