### ISSUE TITLE
Cannot import module Binary

### ISSUE THREAD

**Issue by yuan8421** [py-bson/bson#73]
Hi Community,

I'm pretty new to the bson.
I installed the bson using
```
sudo pip install bson
```
The rosbridge_suit depends on bson, specifically **bson.Binary**
After install the latest version of bson which is 0.5.1, it will argue that

> 'module' object has no attribute 'Binary'
> I did some fix by myself. But it will be good have a official fix for this problem.
I also tried to follow the api page of python
https://api.mongodb.com/python/2.7.2/api/bson/binary.html
to import Binary using
```
from bson.binary import Binary
```
It argues

> >>> from bson.binary import Binary
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named binary

I have fix it by some ugly modification. But if anyone could tell me what happened will be great!

**Comment by Rubiel1** [comment]
Hi,
I installed "bson-0.5.6" and I have similar problem 

>     from bson.binary import Binary
>     ImportError: No module named binary


How did you solve it @yuan8421  ?

**Comment by Rubiel1** [comment]
Well, my solution was to work with MongoDB.

**Comment by Parkayun** [comment]
You should install pymongo instead of bson. it's different package.

**Comment by banderlog** [comment]
You should install `bson` and THAN `pymongo`. After it you will be able to do `bson.Binary`. From #82
