### ISSUE TITLE
pip install bson error, pip verion is 10.0.0

### ISSUE THREAD

**Issue by willhope** [py-bson/bson#77]
[root@localhost home]# pip -V
pip 10.0.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)
[root@localhost home]# pip install bason
Collecting bason
  Could not find a version that satisfies the requirement bason (from versions: )
No matching distribution found for bason
[root@localhost home]# pip install bson
Collecting bson
  Using cached bson-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-H29FRs/bson/setup.py", line 8, in <module>
        from pip import get_installed_distributions
    ImportError: cannot import name get_installed_distributions
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-H29FRs/bson/

**Comment by phdru** [comment]
`pip` authors were warning for many years to not [`import pip`](https://pip.pypa.io/en/latest/user_guide/#using-pip-from-your-program). Finally at version 10 they restructured their code.

**Comment by Parkayun** [comment]
I will solve this problem with #41 . Also welcome pr before I work.

**Comment by Parkayun** [comment]
0.5.4 released

**Comment by awesomebytes** [comment]
Shouldn't the package depend on `pip`?
I'm running the case with a gentoo that the setup.py fails cause... well, cant import anything from pip cause it's not installed.
