### ISSUE TITLE
ImportError: cannot import name 'abc'

### ISSUE THREAD

**Issue by yangzhao5566** [py-bson/bson#82]
from bson.py3compat import abc, string_type, PY3, text_type
ImportError: cannot import name 'abc'

**Comment by ppython** [comment]
This is frustrating as there is no more tags(versions) on github to easily track the problem

**Comment by JinXJinX** [comment]
uninstall bson, then install pymongo will solve this.

```
pip uninstall bson
pip install pymongo
```

I think another bson package is what you are looking for. https://github.com/mongodb/mongo-python-driver

**Comment by shlomiLan** [comment]
I had to add `pymongo==3.7.2` to my requirements file, with `pymongo==3.7.1` I got this same error.

**Comment by Parkayun** [comment]
It seems that this issue is raising when installed py-bson and pymongo both.
But, this package designed with independent package (don't use pymongo togehter).

If anyone encounter this issue whithout pymongo, please comment it with how to reproduce(environments and more).

Thank you.

**Comment by shlomiLan** [comment]
I'm not using them both, I tried install `pymingo` to fix this bug. 
You can see here in which package s I use https://github.com/shlomiLan/slots_tracker_server/blob/master/requirements.txt

The problem is that I'm not getting this error on my local machine (Mac) or in the CI (Travis), only on heroku.
 Let me know if there is any more information that I can give you.

**Comment by hbrannan** [comment]
There seems to remain a lack of clarity, so, from [the most useful SO post I found](https://stackoverflow.com/questions/53441445/flask-app-broken-after-bson-update-in-heroku) on this issue from [@bauman.space](https://stackoverflow.com/users/3093018/bauman-space): 

```
pymongo>=2.7.1 directive overwrites your bson installation

from https://github.com/mongodb/mongo-python-driver

Do not install the "bson" package from pypi. PyMongo comes with its own bson package; doing easy_install bson or pip install bson installs a third-party package that is incompatible with PyMongo.

assuming you really want to use the 3rd party bson, you'll need to

pip uninstall bson (removes the overwritten bson that landed via pymongo package) pip install bson (reinstalls the py-bson package) or you could patch the pymongo install to remove the collections.abc line (evidently you don't really need it?), but messing with production packaged code is questionable.

pymongo module https://github.com/mongodb/mongo-python-driver/blob/master/bson/py3compat.py#L22-L25

py-bson module you are trying to use. https://github.com/py-bson/bson/blob/master/bson/py3compat.py#L22-L24
```

**Comment by shlomiLan** [comment]
> There seems to remain a lack of clarity, so, from [the most useful SO post I found](https://stackoverflow.com/questions/53441445/flask-app-broken-after-bson-update-in-heroku) on this issue from [@bauman.space](https://stackoverflow.com/users/3093018/bauman-space):
> 
> ```
> pymongo>=2.7.1 directive overwrites your bson installation
> 
> from https://github.com/mongodb/mongo-python-driver
> 
> Do not install the "bson" package from pypi. PyMongo comes with its own bson package; doing easy_install bson or pip install bson installs a third-party package that is incompatible with PyMongo.
> 
> assuming you really want to use the 3rd party bson, you'll need to
> 
> pip uninstall bson (removes the overwritten bson that landed via pymongo package) pip install bson (reinstalls the py-bson package) or you could patch the pymongo install to remove the collections.abc line (evidently you don't really need it?), but messing with production packaged code is questionable.
> 
> pymongo module https://github.com/mongodb/mongo-python-driver/blob/master/bson/py3compat.py#L22-L25
> 
> py-bson module you are trying to use. https://github.com/py-bson/bson/blob/master/bson/py3compat.py#L22-L24
> ```

I posted that question, you can see it in the previous comment :)
Now I get a different but similar error:
```
    Traceback (most recent call last):
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
         worker.init_process()
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
         self.load_wsgi()
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
         self.wsgi = self.app.wsgi()
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
         self.callable = self.load()
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
         return self.load_wsgiapp()
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
         return util.import_app(self.app_uri)
       File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
         __import__(module)
       File "/app/slots_tracker_server/__init__.py", line 5, in <module>
         from mongoengine import connect
       File "/app/.heroku/python/lib/python3.6/site-packages/mongoengine/__init__.py", line 2, in <module>
         from mongoengine import connection
       File "/app/.heroku/python/lib/python3.6/site-packages/mongoengine/connection.py", line 1, in <module>
         from pymongo import MongoClient, ReadPreference, uri_parser
       File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/__init__.py", line 77, in <module>
         from pymongo.collection import ReturnDocument
       File "/app/.heroku/python/lib/python3.6/site-packages/pymongo/collection.py", line 20, in <module>
         from bson.code import Code
       File "/app/.heroku/python/lib/python3.6/site-packages/bson/code.py", line 18, in <module>
         from bson.py3compat import abc, string_type, PY3, text_type
     ModuleNotFoundError: No module named 'bson.py3compat'
```

**Comment by hbrannan** [comment]
I had the same issue. The step I took from your original error to this one was to `pipenv uninstall bson`. I was able to resolve the `No module named 'bson.py3compat'`, though I haven't yet found a better solution that deleting the `.venv` dir and and reinstalling the venv from the Pipfile `pipenv install`. 

It seems as those using virtualenv have similar issues/ suggestions & everything works fine for me now.

**Comment by hbrannan** [comment]
And, haha, yup. Well, thanks for posting.

**Comment by hbrannan** [comment]
Haha, yes, see that now. Well, thanks for posting.

I believe your pymongo file may remain corrupted/ partially overwritten by the earlier bson install. I had this same issue, and per the thread, attempted a pymongo reinstall to resolve. 

My virtual env, however, seems to have a bit of an issue with updating, so reinstalling pymongo did not resolve the issue. 

I deleted the generated .venv repo, and ran a blanket install. Now the issues are resolved for me. 
I am using pipenv & had to create an empty .venv folder for that kind of reinstall to work. From comments online, it appears that people using virtualenv, at least, are having similar issues.

**Comment by shlomiLan** [comment]
I'm running on Heroku so I can't control how the environment is been set up. I run ` heroku repo:purge_cache -a APP_NAME` and redeploy the app from Git and now it seems to be working.

**Comment by jesse-homes** [comment]
I have Python 3.7.0 running in a virtual environment on MacBook Pro Mojave 10.14.3 
I had installed PyMongo before BSON, then doing geo 2d stuff needed BSON.  Added BSON using pypl pip and would not work.  
Uninstalled PyMongo and BSON
Then installed BSON [Successfully installed bson-0.5.7]
Then installed PyMongo [Successfully installed pymongo-3.7.2]
Now it works fine.

**Comment by lionandbull** [comment]
> I had to add `pymongo==3.7.2` to my requirements file, with `pymongo==3.7.1` I got this same error.
> 
> **Update:** still not working properly. My app runs on Heroku and only there I see this issue, can't reproduce on my local machine or on Travis-CI

It works for me.

**Comment by JosephP91** [comment]
> I have Python 3.7.0 running in a virtual environment on MacBook Pro Mojave 10.14.3
> I had installed PyMongo before BSON, then doing geo 2d stuff needed BSON. Added BSON using pypl pip and would not work.
> Uninstalled PyMongo and BSON
> Then installed BSON [Successfully installed bson-0.5.7]
> Then installed PyMongo [Successfully installed pymongo-3.7.2]
> Now it works fine.

Confirmed. If you install bson first and then pymongo, it works.

**Comment by dparkar** [comment]
Coming across the same thing today. Any suggestions on how to detect the root cause ?

**Comment by samhavens** [comment]
@dparkar the following (based on what worked for others in this thread) worked for me:

```sh
pip uninstall -y bson pymongo \
&& pip install bson==0.5.7 \
&& pip install pymongo==3.7.2
```

**Comment by sadakmed** [comment]
@Affan-Ali this guy is great

```
pip uninstall bson
pip uninstall pymongo
conda install -c anaconda pymongo 
```
This solve it, is better to install with conda than pip if u r using anaconda

**Comment by ilfrich** [comment]
This uninstall bson, install pymongo is a hacky solution! I appreciate people figuring this out, but it's not a good way to solve the underlying problem.

I keep running into this issue and found a couple of interesting things. Note that I'm using the `python:3.6` docker image to reproduce this.

The following `pip install -r requirements.txt` will cause the `abc` import issue:

```
pymongo
bson
```

Where, if you put `bson` first, no error:

```
bson
pymongo
```

I'm still investigating the issue further and will update this comment later with steps to repeat.

**Comment by EvdH0** [comment]
Thanks @ilfrich! Especially the transitive dependency complicates things:
> Weirdly, if you have a transitive dependency to bson (e.g. you depend on X and X depends on bson), it works ~50% of the time (I ran the build 10x and it failed half of the time). Weird race condition.

This seems to work for now:
``
bson~=0.5.7
pymongo~=3.7.2
```

**Comment by exaland** [comment]
I have same problem 

I resolved with uninstall with pip and install with pip3

`pip uninstall bson`
`pip uninstall pymongo`

`pip3 install bson`
`pip3 install pymongo`

**Comment by Parkayun** [comment]
guys, I uploaded python to pypi for looking on demands. (same package with bson.)
`pip install pybson` 
#41

**Comment by satendrasingh51** [comment]
This worked for me:

pip uninstall bson
pip uninstall pymongo
pip install pymongo

**Comment by Joshuah143** [comment]
Worth noting that I experienced the same issue today running the latest versions of each package. Solved by removing bson
