### ISSUE TITLE
bson loads a list as a dict

### ISSUE THREAD

**Issue by dzimbeck** [py-bson/bson#89]
if you do the following:
bsonjs.loads(json.dumps([]))

The result is {}

This caused some minor issues in a program I'm working on. Since json is able to load lists I think there is no reason bson shouldn't experience similar behavior.

**Comment by Parkayun** [comment]
what is `bsonjs` ?

**Comment by dzimbeck** [comment]
sorry, I just realized this is the wrong repository and I'm looking for bsonjs
