### ISSUE TITLE
GitHub tags and/or tests in sdist

### ISSUE THREAD

**Issue by jayvdb** [py-bson/bson#95]
I am packaging this for openSUSE, and dont have a way to get the tests for recent releases.
There are no tags in GitHub for recent releases, and there are no tests in the sdist uploaded to PyPI.
fwiw, I would prefer to be fetching only from PyPI, with the tests included via `MANIFEST.in`, but the fallback is a GitHub tag archive, which automatically includes everything.

**Comment by Parkayun** [comment]
I made 0.5.8 release and tags on github.
Thanks :)

**Comment by jayvdb** [comment]
Thanks. Packaging request submitted https://build.opensuse.org/request/show/693035
